### ISSUE TITLE
Use deal cheatcode to set token balances in setup of 'AddLiquid.t.sol' 

### ISSUE THREAD

**Issue by BlockChomper** [RareSkills/uniswap-v2-puzzles#1]
Currently within the test setup -  we're trying to call transfer directly on IUniswapV2Pair(weth) and IUniswapV2Pair(usdc), but WETH and USDC are ERC20 tokens, not Uniswap pairs. The current setup will cause the test to revert with the completed challenge code as the prank calls are targeting specific addresses that might not have had the tokens to transfer

```solidity
   function setUp() public {
        addLiquid = new AddLiquid();

        // transfers 1 WETH to addLiquid contract
        vm.prank(0xF04a5cC80B1E94C69B48f5ee68a08CD2F09A7c3E);
        IUniswapV2Pair(weth).transfer(address(addLiquid), 1 ether);

        // transfers 1000 USDC to addLiquid contract
        vm.prank(0x4B16c5dE96EB2117bBE5fd171E4d203624B014aa);
        IUniswapV2Pair(usdc).transfer(address(addLiquid), 1000 * 10 ** 6);
    }
```
Suggest using Foundry's deal cheatcode to set the token balances directly. 

```solidity
 function setUp() public {
        addLiquid = new AddLiquid();
        
        // Deal WETH to our test contract
        deal(weth, address(addLiquid), 1 ether);
        
        // Deal USDC to our test contract
        deal(usdc, address(addLiquid), 1000 * 10**6);
    }
```

**Comment by tanim0la** [comment]
The usdc address i was transferring from ran out of funds. Pushed the suggest changes to all the tests
